/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IMockWormhole__factory } from "./IMockWormhole__factory";
export { MockDotRegistry__factory } from "./MockDotRegistry__factory";
export { MockWormhole__factory } from "./MockWormhole__factory";
