/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMockWormhole } from "./IMockWormhole";
export type { MockDotRegistry } from "./MockDotRegistry";
export type { MockWormhole } from "./MockWormhole";
