/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as interfaces from "./interfaces";
import type * as mock from "./mock";

export type { interfaces };

export type { mock };
export type { DotRegistry } from "./DotRegistry";
