/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export * as mock from "./mock";
export { DotRegistry__factory } from "./DotRegistry__factory";
