/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BridgeGetters } from "./BridgeGetters";
export type { ITokenBridge } from "./ITokenBridge";
export type { IWormhole } from "./IWormhole";
export type { PortalWrappedToken } from "./PortalWrappedToken";
